Add cleanup activity for Integrated Service v2
banzaicloud/pipeline pull request #3440
Opened 2021-02-18 10:15 UTC by colin014

| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| API breaks?     | no
| Deprecations?   | no
| Related tickets | fixes #3413
| License         | Apache 2.0

### What's in this PR?
Disable all of v2 Integrated Service before running `delete-cluster` activity

### Checklist

- [x] Implementation tested (with at least one cloud provider)
- [x] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)

### To Do

- [ ] Force delete
- [ ] Testing cluster delete with v1 Integrated Service 
- [ ] Is cluster managed

2021-02-18 21:18 UTC, pepov requested changes

2021-02-18 21:18 UTC, pepov commented on internal/integratedservices/registry.go
> +func (r integratedServiceOperatorRegistry) DisableServiceInstance(ctx context.Context, clusterID uint) error {
we should put this functionality in a separate class, it doesn't belong here

2021-02-18 21:18 UTC, pepov commented on internal/integratedservices/registry.go
> +		item.Spec.Enabled = utils.BoolPointer(false)
check if the spec is already disabled, because then we don't have to disable it again

2021-02-18 21:18 UTC, pepov commented on internal/integratedservices/registry.go
> +
I don't understand why we would need this
```suggestion
```

2021-02-18 21:18 UTC, pepov commented on internal/integratedservices/registry.go
> +		}
```suggestion
		key := types.NamespacedName{
			Namespace: item.Namespace,
			Name:      item.Name,
		}
```

2021-02-18 21:18 UTC, pepov commented on internal/integratedservices/registry.go
> +		}
```suggestion
		if err := clusterClient.Update(ctx, &item); err != nil {
			return errors.Wrap(err, "failed to disable the integrated service")
		}
```

2021-02-18 21:18 UTC, pepov commented on internal/integratedservices/registry.go
> +
```suggestion
```
clusterClient is already created above

2021-02-18 21:18 UTC, pepov commented on internal/integratedservices/registry.go
> +			if err := cli.Get(ctx, key, &inactiveSI); err != nil {
```suggestion
			if err := clusterClient.Get(ctx, key, &inactiveSI); err != nil {
```

2021-02-18 21:18 UTC, pepov commented on internal/integratedservices/integratedserviceadapter/workflow/integrated_service_clean_activity.go
> +	if input.Force {
```suggestion
	if err != nil && input.Force {
```

2021-02-24 09:33 UTC, colin014 commented
thx @pepov for the review! I updated the branch with the reqested changes

2021-02-24 12:09 UTC, pepov commented on internal/integratedservices/interface.go
> +type IntegratedSeriviceCleaner interface {
```suggestion
type IntegratedServiceCleaner interface {
```

2021-02-24 12:09 UTC, pepov commented on internal/integratedservices/interface.go
> +type ServiceInstanceDisabler interface {
why is this separate interface needed?

2021-02-24 12:09 UTC, pepov commented on internal/integratedservices/cleanup.go
> +			*item.Spec.Enabled == true {
maybe I suggested this, but when cleaning the cluster we should disable all services not just the ones managed by pipeline

```suggestion
		if utils.PointerToBool(item.Spec.Enabled) {
```

2021-02-24 16:33 UTC, lpuskas approved these changes
lgtm

2021-02-24 16:33 UTC, lpuskas commented on internal/integratedservices/cleanup.go
> +type integratedServiceClean struct {
I'd name the struct `integratedServiceCleaner`

2021-02-26 12:40 UTC, pepov commented on internal/integratedservices/cleanup.go
> +			}
I would put this in a separate iteration over all the service items for the following reason:
if one of the services cannot reach the uninstalled/uninstallfailed state the rest of the services wont be removed even if we force remove the cluster

2021-03-04 11:09 UTC, pepov approved these changes

2021-03-04 11:12 UTC, merged