install helm-s3 plugin
banzaicloud/pipeline pull request #3488
Opened 2021-04-28 13:35 UTC by sancyx

| Q               | A
| --------------- | ---
| Bug fix?        | no|yes
| New feature?    | no|yes
| API breaks?     | no|yes
| Deprecations?   | no|yes
| Related tickets | fixes #X, partially #Y, mentioned in #Z
| License         | Apache 2.0

### What's in this PR?

### Why?

### Additional context

### Checklist

- [ ] Implementation tested (with at least one cloud provider)
- [ ] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
- [ ] OpenAPI and Postman files updated (if needed)
- [ ] User guide and development docs updated (if needed)
- [ ] Related Helm chart(s) updated (if needed)

### To Do

- [ ] If the PR is not complete but you want to discuss the approach, list what remains to be done here

2021-04-30 10:41 UTC, lpuskas approved these changes

2021-05-04 07:53 UTC, pregnor requested changes

2021-05-04 07:53 UTC, pregnor commented on internal/helm/helmadapter/helm3_env_service.go
> +		buffer, err := client.Get(repoUrl)
**Required**: this solution only works if the Helm S3 repository is in the same region where the AWS credential context is.

0. I have everything configured locally to `eu-central-1` by default (AWS credentials, Pipeline secret, everything).

1. I created a Helm S3 repo in us-west-1 and uploaded the NPLS chart there according to the Helm S3 guide.

2. I added the following to my local Pipeline control-plane configuration:
```yaml
cluster:
    labels:
        domain: banzaicloud.io
        forbiddenDomains:
            [
                "k8s.io",
                "kubernetes.io",
                "google.com",
                "coreos.com",
                "oraclecloud.com",
                "node.info",
                "azure.com",
                "agentpool",
                "storageprofile",
                "storagetier",
            ]

        charts:
            nodepoolLabelOperator:
                chart: "s3/nodepool-labels-operator"
                version: "0.1.1"

helm:
    home: "./var/cache"
    repositories:
        stable: "https://charts.helm.sh/stable"
        banzaicloud-stable: "https://kubernetes-charts.banzaicloud.com"
        bitnami: "https://charts.bitnami.com/bitnami"
        loki: "https://grafana.github.io/loki/charts"
        prometheus-community: "https://prometheus-community.github.io/helm-charts"
        s3: "s3://my-bucket-from-us-west-1/stable/charts"
```

3. I started a simple cluster creation with this configuration:
```yaml
{
  "cloud": "amazon",
  "location": "eu-central-1",
  "name": "pregnor-pipeline-helm-s3-test",
  "properties": {
    "eks": {
      "nodePools": {
        "pool1": {
          "autoscaling": true,
          "count": 3,
          "instanceType": "t3a.medium",
          "maxCount": 10,
          "minCount": 1,
          "tags": {
            "nodePoolTag": "NodePoolTagValue"
          }
        }
      },
      "tags": {
        "clusterTag": "clusterTagValue"
      },
      "version": "1.18"
    }
  },
  "secretName": "my-secret"
}
```

4. The cluster creation failed at the NPLS installation step.
```shell
ERRO[1577] Activity error.
    ActivityType=install-nodepool-labelset-operator
    Domain=pipeline RunID=3c765d83-62cb-4d72-870c-b3e1fae24b5f 
    TaskList=pipeline 
    WorkerID=14912@localhost@pipeline 
    WorkflowID=942f1e6c-f037-4943-b60b-309b02f3e127_2 
    application=pipeline.worker 
    component=cadence-worker 
    environment=production 
    error="installing NodePoolLabelSet operator failed: failed to install release: failed to locate chart: failed to download \"s3/nodepool-labels-operator\" at version \"0.1.1\" (hint: running `helm repo update` may help)" errorVerbose="failed to download \"s3/nodepool-labels-operator\" at version \"0.1.1\" (hint: running `helm repo update` may help)
helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart
	_build/helm.sh/helm/v3/pkg/action/install.go:690
github.com/banzaicloud/pipeline/internal/helm/helmadapter.releaser.Install
	internal/helm/helmadapter/releaser_service.go:99
github.com/banzaicloud/pipeline/internal/helm.service.InstallRelease
	internal/helm/service.go:470
github.com/banzaicloud/pipeline/internal/helm/helmadapter.(*helm3UnifiedReleaser).InstallDeployment
	internal/helm/helmadapter/helm_service.go:168
github.com/banzaicloud/pipeline/internal/cluster/clustersetup.InstallNodePoolLabelSetOperatorActivity.Execute
	internal/cluster/clustersetup/activity_install_nodepool_labelset_operator.go:67
reflect.Value.call
	/usr/local/Cellar/go/1.16.3/libexec/src/reflect/value.go:476
reflect.Value.Call
	/usr/local/Cellar/go/1.16.3/libexec/src/reflect/value.go:337
go.uber.org/cadence/internal.(*activityExecutor).Execute
	_build/go.uber.org/cadence/internal/internal_worker.go:731
go.uber.org/cadence/internal.(*activityTaskHandlerImpl).Execute
	_build/go.uber.org/cadence/internal/internal_task_handlers.go:1822
go.uber.org/cadence/internal.(*activityTaskPoller).ProcessTask
	_build/go.uber.org/cadence/internal/internal_task_pollers.go:1014
go.uber.org/cadence/internal.(*baseWorker).processTask
	_build/go.uber.org/cadence/internal/internal_worker_base.go:323
runtime.goexit
	/usr/local/Cellar/go/1.16.3/libexec/src/runtime/asm_amd64.s:1371
failed to locate chart
failed to install release
installing NodePoolLabelSet operator failed"
```

5. I created a Helm S3 repo in eu-central-1 and uploaded the NPLS chart there too.

6. I reconfigured my Pipeline control-plane to use the eu-central-1 Helm S3 repo for the NPLS chart and restarted both the API server and the worker.

7. The worker successfully installed the NPLS on the managed cluster afterwards and the cluster creation finished successfully.

For more information see the [plugin's documentation](https://github.com/hypnoglow/helm-s3#s3-bucket-location).

There are 2 ways to resolve this: either we have to wait for the dynamic bucket region PR to be merged and released in the original helm-s3 plugin or we have to use our fork of the plugin here as well as in the installer which is still WIP (trying to finish it ASAP).

2021-05-05 07:39 UTC, sancyx commented on docs/developer.md
> +In case you don't have helm installed you can download helm-s3 plugin from [here](), extract it to a `helm-plugins` folder and set `HELM_PLUGINS=helm-plugins` when starting Pipeline.
fixed

2021-05-18 10:29 UTC, sagikazarmark commented on Dockerfile
> +FROM alpine:3.12 AS helms3
```suggestion
FROM alpine:3.13 AS helms3
```

2021-05-18 10:29 UTC, sagikazarmark commented on Dockerfile
> -
???

2021-05-21 08:08 UTC, pregnor commented on Dockerfile
> -
Fixed in d894661.

2021-05-21 08:08 UTC, pregnor commented on Dockerfile
> +FROM alpine:3.12 AS helms3
Fixed in d894661.

2021-05-21 08:54 UTC, pregnor commented on internal/helm/helmadapter/helm3_env_service.go
> +		buffer, err := client.Get(repoUrl)
Fixed in d894661.

2021-05-21 08:57 UTC, pregnor commented
Updated the PR with our plugin fork to use dynamic bucket regions.

Retested using the first part of the test mentioned in my change request thread (the part which failed using an S3 bucket in a different region).
Using the new Banzai Cloud plugin fork makes the cluster creation work with S3 buckets in other regions than the locally configured one as well so I guess the feature implementation is complete now.

Also addressed the review comments.

2021-05-21 13:05 UTC, pregnor approved these changes

2021-05-26 06:36 UTC, merged